### PR TITLE
Make usage of the routing API more flexible

### LINKED ISSUE #41: Make Client more flexible
An issue with the client right now is that if we add new parameters to the API, we have to [change the client](https://github.com/graphhopper/directions-api-js-client/blob/master/src/GraphHopperRouting.js#L58) as well.

It would be great if we could make the client a bit more flexible. We could dynamically convert the args object into a request string and only add special handling for a few parameters or maybe we add a second route method that accepts a URL so that users can write their own url conversion if needed.

### PR DESCRIPTION
**Pull request by boldtrn**
Fixes #41. 

With this PR the routing API becomes more flexible. It's possible to pass either a QueryString as String or to an Object. The object is parsed dynamically, so if we change the routing API, we don't need to update the client anymore.

One issue is the avoid parameter. It works different than most other parameters. So the new method breaks the way of passing these to the client. Earlier one would pass `avoid: [ 'motorway', 'toll' ]` now it's `avoid: 'motorway,toll'`. We could add a special rule for the avoid parameter?

This could also change the behavior for #42, so we should probably check and improve this before releasing 0.10?

Something else we could do before 0.10 is to use the same logic for the other APIs as well and replace all individual `getParametersAsQueryString` with a global method?

BTW: I also updated some dependencies

### CODE REVIEW

**Comment by boldtrn** [comment]
> Ok, let's do this change but maybe put a breaking change note into the release info?

Ok, sure :)

> Isn't it 0.11?

I think we haven't released version .10 as js client yet :). That's what I meant, so I would probably do this sooner than later and when we release a new version, we can introduce breaking changes.

**Comment by karussell** [comment]
:+1:

**Comment by boldtrn** [comment]
Should I create a Changelog file and add this change there?

**Comment by karussell** [comment]
ok

**Comment by boldtrn** [comment]
Ok, I added a CHANGELOG file. Can we merge this PR or should we add/change anything?

**Pull request merged**
