### PR TITLE
Added derequire

### PR DESCRIPTION
**Pull request by boldtrn**
When testing to install this from npmjs I stumbled over an interesting issue. Browserify does not resolve all the require statements in the code. The result is that not all references can be resolved. So I looked at other packages. Some use derequire. Esentially this renames the require statements to dereq. Which fixes the issue that some require statements cannot be resolved.

Samples for derequire:
https://github.com/perliedman/leaflet-routing-machine/blob/master/package.json#L10
https://nolanlawson.com/2015/10/19/the-struggles-of-publishing-a-javascript-library/

Some more information:
https://github.com/calvinmetcalf/derequire/issues/25

On the other hand there are a lot of libs, that don't use it, so I am not sure if there would a different way.

What I find extremely weird about derequire, is that the [repo](https://github.com/calvinmetcalf/derequire) only has about 50 stars, but was downloaded ~180.000 times in the last month, according to [npmjs](https://www.npmjs.com/package/derequire).

As it seems to be some kind of standard procedure, I would just use it and don't bother. WDYT?

### CODE REVIEW

**Comment by karussell** [comment]
This sounds strange. So is this not a bug in browserify? I do not understand the issue fully ...

The package seems to consist of only 32 lines of code:
https://github.com/calvinmetcalf/derequire/blob/master/bin/cmd.js

Not sure if we should rely on an external source for just this and reminds me of the [left-pad story](https://arstechnica.com/information-technology/2016/03/rage-quit-coder-unpublished-17-lines-of-javascript-and-broke-the-internet/) ;)

**Comment by boldtrn** [comment]
Yes, I don't fully understand that either. So browserify leaves require statements in the code, but puts the content of the file in the resulting file. However, when importing the files via npm the require statements cannot be resolved. The lib just renames require statements to dereq. Which is a simple fix. Not sure how to fix this otherwise. Do you have an idea?

**Comment by karussell** [comment]
Ok, lets use it ... it won't break production systems I think.

**Comment by boldtrn** [comment]
> Ok, lets use it ... it won't break production systems I think if it gets unavailable.

Yes, it won't. This is only a dev dependency. This is only needed for building the client, not using it. So if it would be removed from npm, we would need something else to release the next version of the js client.

**Pull request merged**
